-- =====================================================================
-- World Cup Data Hub · 005 · Seed de catálogos
-- 16 sedes · 211 selecciones FIFA · 22 ediciones históricas + Mundial 2026
-- =====================================================================

insert into sedes (nombre_estadio, ciudad, pais, capacidad) values
  ('Estadio Azteca', 'Ciudad de México', 'México', 87523),
  ('Estadio BBVA', 'Monterrey', 'México', 53500),
  ('Estadio Akron', 'Guadalajara', 'México', 48071),
  ('BC Place', 'Vancouver', 'Canadá', 54500),
  ('BMO Field', 'Toronto', 'Canadá', 45500),
  ('MetLife Stadium', 'Nueva York / Nueva Jersey', 'Estados Unidos', 82500),
  ('AT&T Stadium', 'Dallas', 'Estados Unidos', 80000),
  ('NRG Stadium', 'Houston', 'Estados Unidos', 72220),
  ('Arrowhead Stadium', 'Kansas City', 'Estados Unidos', 76416),
  ('Levi''s Stadium', 'San Francisco Bay Area', 'Estados Unidos', 68500),
  ('SoFi Stadium', 'Los Ángeles', 'Estados Unidos', 70240),
  ('Lumen Field', 'Seattle', 'Estados Unidos', 69000),
  ('Mercedes-Benz Stadium', 'Atlanta', 'Estados Unidos', 71000),
  ('Hard Rock Stadium', 'Miami', 'Estados Unidos', 65326),
  ('Gillette Stadium', 'Boston', 'Estados Unidos', 65878),
  ('Lincoln Financial Field', 'Filadelfia', 'Estados Unidos', 69796)
on conflict (nombre_estadio, ciudad) do nothing;

insert into equipos (nombre_equipo, codigo_pais, confederacion, bandera) values
  ('Argentina', 'ARG', 'CONMEBOL', '🇦🇷'),
  ('Brasil', 'BRA', 'CONMEBOL', '🇧🇷'),
  ('Uruguay', 'URU', 'CONMEBOL', '🇺🇾'),
  ('Colombia', 'COL', 'CONMEBOL', '🇨🇴'),
  ('Chile', 'CHI', 'CONMEBOL', '🇨🇱'),
  ('Perú', 'PER', 'CONMEBOL', '🇵🇪'),
  ('Ecuador', 'ECU', 'CONMEBOL', '🇪🇨'),
  ('Paraguay', 'PAR', 'CONMEBOL', '🇵🇾'),
  ('Bolivia', 'BOL', 'CONMEBOL', '🇧🇴'),
  ('Venezuela', 'VEN', 'CONMEBOL', '🇻🇪'),
  ('Francia', 'FRA', 'UEFA', '🇫🇷'),
  ('Inglaterra', 'ENG', 'UEFA', '🏴󠁧󠁢󠁥󠁮󠁧󠁿'),
  ('Bélgica', 'BEL', 'UEFA', '🇧🇪'),
  ('Países Bajos', 'NED', 'UEFA', '🇳🇱'),
  ('Portugal', 'POR', 'UEFA', '🇵🇹'),
  ('España', 'ESP', 'UEFA', '🇪🇸'),
  ('Italia', 'ITA', 'UEFA', '🇮🇹'),
  ('Alemania', 'GER', 'UEFA', '🇩🇪'),
  ('Croacia', 'CRO', 'UEFA', '🇭🇷'),
  ('Dinamarca', 'DEN', 'UEFA', '🇩🇰'),
  ('Suiza', 'SUI', 'UEFA', '🇨🇭'),
  ('Austria', 'AUT', 'UEFA', '🇦🇹'),
  ('Ucrania', 'UKR', 'UEFA', '🇺🇦'),
  ('Suecia', 'SWE', 'UEFA', '🇸🇪'),
  ('Polonia', 'POL', 'UEFA', '🇵🇱'),
  ('Gales', 'WAL', 'UEFA', '🏴󠁧󠁢󠁷󠁬󠁳󠁿'),
  ('Serbia', 'SRB', 'UEFA', '🇷🇸'),
  ('Türkiye', 'TUR', 'UEFA', '🇹🇷'),
  ('Escocia', 'SCO', 'UEFA', '🏴󠁧󠁢󠁳󠁣󠁴󠁿'),
  ('Hungría', 'HUN', 'UEFA', '🇭🇺'),
  ('Noruega', 'NOR', 'UEFA', '🇳🇴'),
  ('República Checa', 'CZE', 'UEFA', '🇨🇿'),
  ('Grecia', 'GRE', 'UEFA', '🇬🇷'),
  ('Rumania', 'ROU', 'UEFA', '🇷🇴'),
  ('Eslovaquia', 'SVK', 'UEFA', '🇸🇰'),
  ('Eslovenia', 'SVN', 'UEFA', '🇸🇮'),
  ('Irlanda', 'IRL', 'UEFA', '🇮🇪'),
  ('Irlanda del Norte', 'NIR', 'UEFA', '🏴'),
  ('Islandia', 'ISL', 'UEFA', '🇮🇸'),
  ('Finlandia', 'FIN', 'UEFA', '🇫🇮'),
  ('Bosnia y Herzegovina', 'BIH', 'UEFA', '🇧🇦'),
  ('Albania', 'ALB', 'UEFA', '🇦🇱'),
  ('Macedonia del Norte', 'MKD', 'UEFA', '🇲🇰'),
  ('Georgia', 'GEO', 'UEFA', '🇬🇪'),
  ('Israel', 'ISR', 'UEFA', '🇮🇱'),
  ('Bulgaria', 'BUL', 'UEFA', '🇧🇬'),
  ('Montenegro', 'MNE', 'UEFA', '🇲🇪'),
  ('Bielorrusia', 'BLR', 'UEFA', '🇧🇾'),
  ('Armenia', 'ARM', 'UEFA', '🇦🇲'),
  ('Luxemburgo', 'LUX', 'UEFA', '🇱🇺'),
  ('Kosovo', 'KVX', 'UEFA', '🇽🇰'),
  ('Azerbaiyán', 'AZE', 'UEFA', '🇦🇿'),
  ('Kazajistán', 'KAZ', 'UEFA', '🇰🇿'),
  ('Estonia', 'EST', 'UEFA', '🇪🇪'),
  ('Letonia', 'LVA', 'UEFA', '🇱🇻'),
  ('Lituania', 'LTU', 'UEFA', '🇱🇹'),
  ('Chipre', 'CYP', 'UEFA', '🇨🇾'),
  ('Islas Feroe', 'FRO', 'UEFA', '🇫🇴'),
  ('Moldavia', 'MDA', 'UEFA', '🇲🇩'),
  ('Malta', 'MLT', 'UEFA', '🇲🇹'),
  ('Andorra', 'AND', 'UEFA', '🇦🇩'),
  ('Gibraltar', 'GIB', 'UEFA', '🇬🇮'),
  ('Liechtenstein', 'LIE', 'UEFA', '🇱🇮'),
  ('San Marino', 'SMR', 'UEFA', '🇸🇲'),
  ('Rusia', 'RUS', 'UEFA', '🇷🇺'),
  ('Estados Unidos', 'USA', 'CONCACAF', '🇺🇸'),
  ('México', 'MEX', 'CONCACAF', '🇲🇽'),
  ('Canadá', 'CAN', 'CONCACAF', '🇨🇦'),
  ('Costa Rica', 'CRC', 'CONCACAF', '🇨🇷'),
  ('Panamá', 'PAN', 'CONCACAF', '🇵🇦'),
  ('Jamaica', 'JAM', 'CONCACAF', '🇯🇲'),
  ('Honduras', 'HON', 'CONCACAF', '🇭🇳'),
  ('El Salvador', 'SLV', 'CONCACAF', '🇸🇻'),
  ('Guatemala', 'GUA', 'CONCACAF', '🇬🇹'),
  ('Curazao', 'CUW', 'CONCACAF', '🇨🇼'),
  ('Haití', 'HAI', 'CONCACAF', '🇭🇹'),
  ('Trinidad y Tobago', 'TRI', 'CONCACAF', '🇹🇹'),
  ('Surinam', 'SUR', 'CONCACAF', '🇸🇷'),
  ('Guyana', 'GUY', 'CONCACAF', '🇬🇾'),
  ('Nicaragua', 'NCA', 'CONCACAF', '🇳🇮'),
  ('República Dominicana', 'DOM', 'CONCACAF', '🇩🇴'),
  ('Cuba', 'CUB', 'CONCACAF', '🇨🇺'),
  ('Antigua y Barbuda', 'ATG', 'CONCACAF', '🇦🇬'),
  ('San Cristóbal y Nieves', 'SKN', 'CONCACAF', '🇰🇳'),
  ('Belice', 'BLZ', 'CONCACAF', '🇧🇿'),
  ('Bermudas', 'BER', 'CONCACAF', '🇧🇲'),
  ('Granada', 'GRN', 'CONCACAF', '🇬🇩'),
  ('San Vicente y las Granadinas', 'VIN', 'CONCACAF', '🇻🇨'),
  ('Barbados', 'BRB', 'CONCACAF', '🇧🇧'),
  ('Puerto Rico', 'PUR', 'CONCACAF', '🇵🇷'),
  ('Santa Lucía', 'LCA', 'CONCACAF', '🇱🇨'),
  ('Dominica', 'DMA', 'CONCACAF', '🇩🇲'),
  ('Montserrat', 'MSR', 'CONCACAF', '🇲🇸'),
  ('Islas Caimán', 'CAY', 'CONCACAF', '🇰🇾'),
  ('Bahamas', 'BAH', 'CONCACAF', '🇧🇸'),
  ('Aruba', 'ARU', 'CONCACAF', '🇦🇼'),
  ('Islas Vírgenes de EE. UU.', 'VIR', 'CONCACAF', '🇻🇮'),
  ('Islas Vírgenes Británicas', 'VGB', 'CONCACAF', '🇻🇬'),
  ('Anguila', 'AIA', 'CONCACAF', '🇦🇮'),
  ('Islas Turcas y Caicos', 'TCA', 'CONCACAF', '🇹🇨'),
  ('Marruecos', 'MAR', 'CAF', '🇲🇦'),
  ('Senegal', 'SEN', 'CAF', '🇸🇳'),
  ('Egipto', 'EGY', 'CAF', '🇪🇬'),
  ('Argelia', 'ALG', 'CAF', '🇩🇿'),
  ('Nigeria', 'NGA', 'CAF', '🇳🇬'),
  ('Costa de Marfil', 'CIV', 'CAF', '🇨🇮'),
  ('Túnez', 'TUN', 'CAF', '🇹🇳'),
  ('Camerún', 'CMR', 'CAF', '🇨🇲'),
  ('Malí', 'MLI', 'CAF', '🇲🇱'),
  ('Ghana', 'GHA', 'CAF', '🇬🇭'),
  ('Sudáfrica', 'RSA', 'CAF', '🇿🇦'),
  ('Burkina Faso', 'BFA', 'CAF', '🇧🇫'),
  ('RD del Congo', 'COD', 'CAF', '🇨🇩'),
  ('Cabo Verde', 'CPV', 'CAF', '🇨🇻'),
  ('Guinea', 'GUI', 'CAF', '🇬🇳'),
  ('Gabón', 'GAB', 'CAF', '🇬🇦'),
  ('Zambia', 'ZAM', 'CAF', '🇿🇲'),
  ('Angola', 'ANG', 'CAF', '🇦🇴'),
  ('Uganda', 'UGA', 'CAF', '🇺🇬'),
  ('Benín', 'BEN', 'CAF', '🇧🇯'),
  ('Guinea Ecuatorial', 'EQG', 'CAF', '🇬🇶'),
  ('Mozambique', 'MOZ', 'CAF', '🇲🇿'),
  ('Madagascar', 'MAD', 'CAF', '🇲🇬'),
  ('Mauritania', 'MTN', 'CAF', '🇲🇷'),
  ('Zimbabue', 'ZIM', 'CAF', '🇿🇼'),
  ('Namibia', 'NAM', 'CAF', '🇳🇦'),
  ('Kenia', 'KEN', 'CAF', '🇰🇪'),
  ('Libia', 'LBY', 'CAF', '🇱🇾'),
  ('Togo', 'TOG', 'CAF', '🇹🇬'),
  ('Sierra Leona', 'SLE', 'CAF', '🇸🇱'),
  ('Congo', 'CGO', 'CAF', '🇨🇬'),
  ('Sudán', 'SDN', 'CAF', '🇸🇩'),
  ('Comoras', 'COM', 'CAF', '🇰🇲'),
  ('Malaui', 'MWI', 'CAF', '🇲🇼'),
  ('Tanzania', 'TAN', 'CAF', '🇹🇿'),
  ('Ruanda', 'RWA', 'CAF', '🇷🇼'),
  ('Níger', 'NIG', 'CAF', '🇳🇪'),
  ('Guinea-Bisáu', 'GNB', 'CAF', '🇬🇼'),
  ('Burundi', 'BDI', 'CAF', '🇧🇮'),
  ('Etiopía', 'ETH', 'CAF', '🇪🇹'),
  ('Liberia', 'LBR', 'CAF', '🇱🇷'),
  ('Botsuana', 'BOT', 'CAF', '🇧🇼'),
  ('Lesoto', 'LES', 'CAF', '🇱🇸'),
  ('Suazilandia', 'SWZ', 'CAF', '🇸🇿'),
  ('Chad', 'CHA', 'CAF', '🇹🇩'),
  ('Gambia', 'GAM', 'CAF', '🇬🇲'),
  ('Sudán del Sur', 'SSD', 'CAF', '🇸🇸'),
  ('Yibuti', 'DJI', 'CAF', '🇩🇯'),
  ('Somalia', 'SOM', 'CAF', '🇸🇴'),
  ('Mauricio', 'MRI', 'CAF', '🇲🇺'),
  ('Santo Tomé y Príncipe', 'STP', 'CAF', '🇸🇹'),
  ('Seychelles', 'SEY', 'CAF', '🇸🇨'),
  ('Eritrea', 'ERI', 'CAF', '🇪🇷'),
  ('República Centroafricana', 'CTA', 'CAF', '🇨🇫'),
  ('Japón', 'JPN', 'AFC', '🇯🇵'),
  ('Irán', 'IRN', 'AFC', '🇮🇷'),
  ('Corea del Sur', 'KOR', 'AFC', '🇰🇷'),
  ('Australia', 'AUS', 'AFC', '🇦🇺'),
  ('Qatar', 'QAT', 'AFC', '🇶🇦'),
  ('Arabia Saudita', 'KSA', 'AFC', '🇸🇦'),
  ('Irak', 'IRQ', 'AFC', '🇮🇶'),
  ('Uzbekistán', 'UZB', 'AFC', '🇺🇿'),
  ('Emiratos Árabes Unidos', 'UAE', 'AFC', '🇦🇪'),
  ('Jordania', 'JOR', 'AFC', '🇯🇴'),
  ('Omán', 'OMA', 'AFC', '🇴🇲'),
  ('Baréin', 'BHR', 'AFC', '🇧🇭'),
  ('China', 'CHN', 'AFC', '🇨🇳'),
  ('Siria', 'SYR', 'AFC', '🇸🇾'),
  ('Palestina', 'PLE', 'AFC', '🇵🇸'),
  ('Vietnam', 'VIE', 'AFC', '🇻🇳'),
  ('Kirguistán', 'KGZ', 'AFC', '🇰🇬'),
  ('India', 'IND', 'AFC', '🇮🇳'),
  ('Tailandia', 'THA', 'AFC', '🇹🇭'),
  ('Líbano', 'LBN', 'AFC', '🇱🇧'),
  ('Tayikistán', 'TJK', 'AFC', '🇹🇯'),
  ('Corea del Norte', 'PRK', 'AFC', '🇰🇵'),
  ('Malasia', 'MAS', 'AFC', '🇲🇾'),
  ('Filipinas', 'PHI', 'AFC', '🇵🇭'),
  ('Turkmenistán', 'TKM', 'AFC', '🇹🇲'),
  ('Hong Kong', 'HKG', 'AFC', '🇭🇰'),
  ('Kuwait', 'KUW', 'AFC', '🇰🇼'),
  ('Myanmar', 'MYA', 'AFC', '🇲🇲'),
  ('Indonesia', 'IDN', 'AFC', '🇮🇩'),
  ('Yemen', 'YEM', 'AFC', '🇾🇪'),
  ('Afganistán', 'AFG', 'AFC', '🇦🇫'),
  ('Singapur', 'SGP', 'AFC', '🇸🇬'),
  ('Maldivas', 'MDV', 'AFC', '🇲🇻'),
  ('Nepal', 'NEP', 'AFC', '🇳🇵'),
  ('Camboya', 'CAM', 'AFC', '🇰🇭'),
  ('Chinese Taipei', 'TPE', 'AFC', '🇹🇼'),
  ('Mongolia', 'MNG', 'AFC', '🇲🇳'),
  ('Laos', 'LAO', 'AFC', '🇱🇦'),
  ('Macao', 'MAC', 'AFC', '🇲🇴'),
  ('Brunéi', 'BRU', 'AFC', '🇧🇳'),
  ('Timor Oriental', 'TLS', 'AFC', '🇹🇱'),
  ('Pakistán', 'PAK', 'AFC', '🇵🇰'),
  ('Sri Lanka', 'SRI', 'AFC', '🇱🇰'),
  ('Guam', 'GUM', 'AFC', '🇬🇺'),
  ('Bután', 'BHU', 'AFC', '🇧🇹'),
  ('Nueva Zelanda', 'NZL', 'OFC', '🇳🇿'),
  ('Nueva Caledonia', 'NCL', 'OFC', '🇳🇨'),
  ('Islas Salomón', 'SOL', 'OFC', '🇸🇧'),
  ('Fiyi', 'FIJ', 'OFC', '🇫🇯'),
  ('Tahití', 'TAH', 'OFC', '🇵🇫'),
  ('Vanuatu', 'VAN', 'OFC', '🇻🇺'),
  ('Papúa Nueva Guinea', 'PNG', 'OFC', '🇵🇬'),
  ('Samoa', 'SAM', 'OFC', '🇼🇸'),
  ('Islas Cook', 'COK', 'OFC', '🇨🇰'),
  ('Tonga', 'TGA', 'OFC', '🇹🇴'),
  ('Samoa Americana', 'ASA', 'OFC', '🇦🇸'),
  ('Bangladés', 'BAN', 'AFC', '🇧🇩')
on conflict (codigo_pais) do nothing;

insert into ediciones (nombre_edicion, anio, sede, pais_sede, equipos, campeon,
                       subcampeon, goleador, goles_goleador, asistencia_total,
                       promedio_asistencia, partidos, finalizada) values
  ('Uruguay 1930', 1930, 'Uruguay', 'Uruguay', 13, 'Uruguay', 'Argentina', 'Guillermo Stábile', 8, 590549, 32808, 18, true),
  ('Italia 1934', 1934, 'Italia', 'Italia', 16, 'Italia', 'Checoslovaquia', 'Oldřich Nejedlý', 5, 363000, 21353, 17, true),
  ('Francia 1938', 1938, 'Francia', 'Francia', 15, 'Italia', 'Hungría', 'Leônidas', 7, 375700, 20872, 18, true),
  ('Brasil 1950', 1950, 'Brasil', 'Brasil', 13, 'Uruguay', 'Brasil', 'Ademir', 9, 1045246, 47511, 22, true),
  ('Suiza 1954', 1954, 'Suiza', 'Suiza', 16, 'Alemania', 'Hungría', 'Sándor Kocsis', 11, 768607, 29562, 26, true),
  ('Suecia 1958', 1958, 'Suecia', 'Suecia', 16, 'Brasil', 'Suecia', 'Just Fontaine', 13, 819810, 23423, 35, true),
  ('Chile 1962', 1962, 'Chile', 'Chile', 16, 'Brasil', 'Checoslovaquia', 'Garrincha', 4, 893172, 27912, 32, true),
  ('Inglaterra 1966', 1966, 'Inglaterra', 'Inglaterra', 16, 'Inglaterra', 'Alemania', 'Eusébio', 9, 1563135, 48848, 32, true),
  ('México 1970', 1970, 'México', 'México', 16, 'Brasil', 'Italia', 'Gerd Müller', 10, 1673975, 52312, 32, true),
  ('Alemania 1974', 1974, 'Alemania', 'Alemania', 16, 'Alemania', 'Países Bajos', 'Grzegorz Lato', 7, 1865753, 49099, 38, true),
  ('Argentina 1978', 1978, 'Argentina', 'Argentina', 16, 'Argentina', 'Países Bajos', 'Mario Kempes', 6, 1545791, 40679, 38, true),
  ('España 1982', 1982, 'España', 'España', 24, 'Italia', 'Alemania', 'Paolo Rossi', 6, 2109723, 40572, 52, true),
  ('México 1986', 1986, 'México', 'México', 24, 'Argentina', 'Alemania', 'Gary Lineker', 6, 2394031, 46039, 52, true),
  ('Italia 1990', 1990, 'Italia', 'Italia', 24, 'Alemania', 'Argentina', 'Salvatore Schillaci', 6, 2516215, 48389, 52, true),
  ('Estados Unidos 1994', 1994, 'Estados Unidos', 'Estados Unidos', 24, 'Brasil', 'Italia', 'Oleg Salenko', 6, 3587538, 68991, 52, true),
  ('Francia 1998', 1998, 'Francia', 'Francia', 32, 'Francia', 'Brasil', 'Davor Šuker', 6, 2785100, 43517, 64, true),
  ('Corea del Sur 2002', 2002, 'Corea del Sur y Japón', 'Corea del Sur', 32, 'Brasil', 'Alemania', 'Ronaldo', 8, 2705197, 42269, 64, true),
  ('Alemania 2006', 2006, 'Alemania', 'Alemania', 32, 'Italia', 'Francia', 'Miroslav Klose', 5, 3359439, 52491, 64, true),
  ('Sudáfrica 2010', 2010, 'Sudáfrica', 'Sudáfrica', 32, 'España', 'Países Bajos', 'Thomas Müller', 5, 3178856, 49670, 64, true),
  ('Brasil 2014', 2014, 'Brasil', 'Brasil', 32, 'Alemania', 'Argentina', 'James Rodríguez', 6, 3429873, 53591, 64, true),
  ('Rusia 2018', 2018, 'Rusia', 'Rusia', 32, 'Francia', 'Croacia', 'Harry Kane', 6, 3031768, 47371, 64, true),
  ('Qatar 2022', 2022, 'Qatar', 'Qatar', 32, 'Argentina', 'Francia', 'Kylian Mbappé', 8, 3404252, 53191, 64, true)
on conflict (anio) do nothing;

-- Edición en curso: Mundial 2026 (sin campeón todavía → finalizada = false, RN01)
insert into ediciones (nombre_edicion, anio, sede, pais_sede, equipos, campeon,
                       subcampeon, goleador, goles_goleador, asistencia_total,
                       promedio_asistencia, partidos, fecha_inicio, finalizada) values
  ('Norteamérica 2026', 2026, 'Canadá, Estados Unidos y México', 'Estados Unidos',
   48, null, null, null, null, null, null, 104, '2026-06-11', false)
on conflict (anio) do nothing;
